name: Pipeline CI/CD

on:
  push:
    branches:
      -main
    paths # só dispara se arquivos nessas pastas mudarem
      - *src/**" #só mudanças no codigo fonte
      - "-gifthun/workflows/**" #mudanças nos proprios pipelines
    workflow_dispatch: #habilitar o botao "run workflow" no Gifthub actions

    jobs:
    #primeiro job: build
    build:
    runs-on: ubuntu-latest #Imagem da maquina usada no CI

    steps:
     -name: chechout do código
      uses: actions/checkout@v4

      -name: instalação do Node
       uses: actions/setup-node@v4
       with:
       node-version: '20'
       cache: "npm"
       cache-dependency-path: package-lock.json

       - name: Instalação das depêndencias
         run: npm install

        -name: Rodar o build
         run: npm run build

        env:
         TMDB_API_URL: ${{ vars.TMDB_API_URL}}
         TMDB_API_KEY: ${{ secrets.TMDB_API_KEY}}

    tests:
    runs on: ubuntu-latest
    needs: build 

    steps:
     -name: chechout do código
      uses: actions/checkout@v4

      -name: instalação do Node
       uses: actions/setup-node@v4
       with:
       node-version: '20'
       cache: "npm"
       cache-dependency-path: package-lock.json

       -name: Instalação das depêndencias
        run: npm intall

       -name: Rodar lint
        run: npm run lint

        -name: Verificar formatação
        run: npm run format -- -- check
        
        -name: Rodar testes
        run: npm run test
    
